# Generated by Django 4.2.1 on 2023-08-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='是否顶置'),
        ),
    ]
