# Generated by Django 4.2.1 on 2023-07-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title_level',
            field=models.IntegerField(default=4, verbose_name='头衔类别,1站主,2管理员,3特殊,4普通'),
        ),
    ]
