# Generated by Django 4.2.1 on 2023-08-01 05:04

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_sign_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/media/user/avatar/txdefault.jpg', upload_to=user.models.Rename('media/user/avatar'), verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='background_image',
            field=models.ImageField(default='/media/user/userpage_background/backimg.jpg', upload_to=user.models.Rename('media/user/userpage_background'), verbose_name='背景图片'),
        ),
    ]
